name: CI / Deploy

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
          restore-keys: ${{ runner.os }}-clojure
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: DeLaGuardo/setup-clojure@13.6.0
        with:
          cli: latest
      - run: clojure -T:build test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
          restore-keys: ${{ runner.os }}-clojure
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: DeLaGuardo/setup-clojure@13.6.0
        with:
          cli: latest
      - run: clojure -T:build ci
      - run: clojure -T:build deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
